# Generated by Django 4.2.1 on 2023-07-05 21:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FumoSeriesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_series', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='FumoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fumo_name', models.CharField(max_length=45)),
                ('release_year', models.PositiveSmallIntegerField()),
                ('fumo_price', models.PositiveIntegerField()),
                ('fumo_size', models.CharField(max_length=45)),
                ('url_img', models.CharField(max_length=50)),
                ('fumo_serie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fumos_app.fumoseriesmodel')),
            ],
        ),
    ]
