productos = [
    {
        'id':1,
        'nombre': 'Hakurei Reimu Versión 1.0',
        'tipo': 'Fumo Regular',
        'rareza': 'Poco común',
        'descripcion': 'Fumo-Fumo de Hakurei Reimu, Años de lanzamiento: 2008, 2009, 2010, 2011 y 2012.',
        'precio': 1500,
        'cantidad': 13,
        'imagen': '/static/img/Fumo_images/Fumo_type//001.jpg',
    },
    {
        'id':2,
        'nombre': 'Hakurei Reimu Versión de Kourindou',
        'tipo': 'Fumo Regular',
        'rareza': 'Común',
        'descripcion': 'Fumo-Fumo de Hakurei Reimu, Años de lanzamiento: 2015, 2016, 2017, 2018 y 2020.',
        'precio': 1500,
        'cantidad': 4,
        'imagen': '/static/img/Fumo_images/Fumo_type/345.jpg',
    },
    {
        'id':3,
        'nombre': 'Hakurei Reimu Versión 1.5',
        'tipo': 'Fumo Regular',
        'rareza': 'Común',
        'descripcion': 'Fumo-Fumo de Hakurei Reimu, Año de lanzamiento: 2022',
        'precio': 1500,
        'cantidad': 37,
        'imagen': '/static/img/Fumo_images/Fumo_type/897.jpg',
    },
    {
        'id':4,
        'nombre': 'Kirisame Marisa Versión 1.0',
        'tipo': 'Fumo Regular',
        'rareza': 'Poco Común',
        'descripcion': 'Fumo-Fumo de Kirisame Marisa, 2008, 2009, 2010, 2011 y 2012.',
        'precio': 1500,
        'cantidad': 25,
        'imagen': '/static/img/Fumo_images/Fumo_type/002.jpg',
    },
    {
        'id':6,
        'nombre': 'Kirisame Marisa Versión 2.0',
        'tipo': 'Fumo Regular',
        'rareza': 'Raro',
        'descripcion': 'Fumo-Fumo de Kirisame Marisa, Años de lanzamiento: 2014, 2016 y 2020.',
        'precio': 1500,
        'cantidad': 7,
        'imagen': '/static/img/Fumo_images/Fumo_type/278.jpg',
    },
    {
        'id':7,
        'nombre': 'Kirisame Marisa Versión de Kourindou',
        'tipo': 'Fumo Regular',
        'rareza': 'Común',
        'descripcion': 'Fumo-Fumo de Kirisame Marisa, Años de lanzamiento: 2016, 2017, 2018 y 2020.',
        'precio': 1500,
        'cantidad': 42,
        'imagen': '/static/img/Fumo_images/Fumo_type/423.jpg',
    },
    {
        'id':8,
        'nombre': 'Kirisame Marisa Versión 1.5',
        'tipo': 'Fumo Regular',
        'rareza': 'Común',
        'descripcion': 'Fumo-Fumo de Kirisame Marisa, Año de lanzamiento: 2022.',
        'precio': 1500,
        'cantidad': 7,
        'imagen': '/static/img/Fumo_images/Fumo_type/898.jpg',
    },
    {
        'id':9,
        'nombre': 'Cirno Versión 1.0',
        'tipo': 'Fumo Regular',
        'rareza': 'Raro',
        'descripcion': 'Fumo-Fumo de Cirno, Año de lanzamientos: 2009, 2010, 2011 y 2013.',
        'precio': 1500,
        'cantidad': 9,
        'imagen': '/static/img/Fumo_images/Fumo_type/014.jpg',
    },


    {
        'id':10,
        'nombre': 'Izayoi Sakuya Versión 1.0',
        'tipo': 'Fumo Regular',
        'rareza': 'Raro',
        'descripcion': 'Fumo-Fumo de Izayoi Sakuya, Año de lanzamientos: 2009, 2010, 2011 y 2012.',
        'precio': 1500,
        'cantidad': 4,
        'imagen': '/static/img/Fumo_images/Fumo_type/004.jpg',
    },
    {
        'id':11,
        'nombre': 'Izayoi Sakuya Versión de Kourindou',
        'tipo': 'Fumo Regular',
        'rareza': 'Común',
        'descripcion': 'Fumo-Fumo de Izayoi Sakuya, Año de lanzamientos: 2009, 2010, 2011 y 2012.',
        'precio': 1500,
        'cantidad': 13,
        'imagen': '/static/img/Fumo_images/Fumo_type/356.jpg',
    },
    {
        'id':12,
        'nombre': 'Izayoi Sakuya Versión Inu (Perro)',
        'tipo': 'Fumo Regular',
        'rareza': 'Raro',
        'descripcion': 'Fumo-Fumo de Izayoi Sakuya, Año de lanzamientos: 2009, 2010, 2011 y 2012.',
        'precio': 1500,
        'cantidad': 1,
        'imagen': '/static/img/Fumo_images/Fumo_type/inu-sakuya.jpg',
    },
    {
        'id':13,
        'nombre': 'Scarlet Remilia Versión 1.0',
        'tipo': 'Fumo Regular',
        'rareza': 'Común',
        'descripcion': 'Fumo-Fumo de Scarlet Remilia, Año de lanzamientos: 2009, 2010, 2011 y 2012.',
        'precio': 1500,
        'cantidad': 23,
        'imagen': '/static/img/Fumo_images/Fumo_type/005.jpg',
    },
    {
        'id':14,
        'nombre': 'Scarlet Remilia Versión de Kourindou',
        'tipo': 'Fumo Regular',
        'rareza': 'Común',
        'descripcion': 'Fumo-Fumo de Scarlet Remilia, Año de lanzamientos: 2015, 2016, 2017, 2018, 2020 y 2022.',
        'precio': 1500,
        'cantidad': 43,
        'imagen': '/static/img/Fumo_images/Fumo_type/364.jpg',
    },
    {
        'id':15,
        'nombre': 'Scarlet Remilia Versión 1.5',
        'tipo': 'Fumo Regular',
        'rareza': 'Común',
        'descripcion': 'Fumo-Fumo de Scarlet Remilia, Año de lanzamientos: 2019, 2020 y 2022.',
        'precio': 1500,
        'cantidad': 12,
        'imagen': '/static/img/Fumo_images/Fumo_type/686.jpg',
    },
    {
        'id':16,
        'nombre': 'Knowledge Patchouli Versión 1.0',
        'tipo': 'Fumo Regular',
        'rareza': 'Poco común',
        'descripcion': 'Fumo-Fumo de Knowledge Patchouli, Año de lanzamientos: 2009, 2010, 2011 y 2012.',
        'precio': 1500,
        'cantidad': 27,
        'imagen': '/static/img/Fumo_images/Fumo_type/006.jpg',
    },
    {
        'id':17,
        'nombre': 'Knowledge Patchouli Versión 1.5',
        'tipo': 'Fumo Regular',
        'rareza': 'Común',
        'descripcion': 'Fumo-Fumo de Knowledge Patchouli, Año de lanzamientos: 2020, 2021 Y 2022.',
        'precio': 1500,
        'cantidad': 42,
        'imagen': '/static/img/Fumo_images/Fumo_type/492.jpg',
    },
    {
        'id':18,
        'nombre': 'Margatroid Alice Versión 1.0',
        'tipo': 'Fumo Regular',
        'rareza': 'Común',
        'descripcion': 'Fumo-Fumo de Margatroid Alice, Año de lanzamientos: 2009, 2010, 2011 y 2012.',
        'precio': 1500,
        'cantidad': 17,
        'imagen': '/static/img/Fumo_images/Fumo_type/007.jpg',
    },
    {
        'id':19,
        'nombre': 'Margatroid Alice Versión 1.5',
        'tipo': 'Fumo Regular',
        'rareza': 'Común',
        'descripcion': 'Fumo-Fumo de Margatroid Alice, Años de lanzamiento: 2017, 2020, 2021 y 2022.',
        'precio': 1500,
        'cantidad': 17,
        'imagen': '/static/img/Fumo_images/Fumo_type/491.jpg',
    },
    {
        'id':20,
        'nombre': 'Hata no Kokoro Versión 1',
        'tipo': 'Fumo Regular',
        'rareza': 'Común',
        'descripcion': 'Fumo-Fumo de Hata no Kokoro, Años de lanzamiento: 2014, 2015, 2016, 2017, 2018, 2020, 2021 y 2022',
        'precio': 1500,
        'cantidad': 17,
        'imagen': '/static/img/Fumo_images/Fumo_type/310.jpg',
    },    

    


]

productos_nendoroid = [
    {
     'id':1,
        'nombre': 'Hakurei Reimu Versión Nendoroid',
        'tipo': 'Fumo Regular',
        'rareza': 'Raro',
        'descripcion': 'Fumo-Fumo Nendoroid de Hakurei Reimu, Año de lanzamiento: 2011.',
        'precio': 1500,
        'cantidad': 20,
        'imagen': '/static/img/Fumo_images/Nendoroid_type/122.jpg',
    },
    {
     'id':2,
        'nombre': 'Kirisame Marisa Versión Nendoroid',
        'tipo': 'Fumo Regular',
        'rareza': 'Raro',
        'descripcion': 'Fumo-Fumo Nendoroid de Kirisame Marisa, Año de lanzamiento: 2011.',
        'precio': 1500,
        'cantidad': 7,
        'imagen': '/static/img/Fumo_images/Nendoroid_type/030.jpg',
    },
]

productos_deka = [
    {
        'id':1,
        'nombre': 'Hakurei Reimu Deka Versión 1',
        'tipo': 'Fumo Deka',
        'rareza': 'Super Raro',
        'descripcion': 'Fumo-Fumo Deka de Hakurei Reimu, Años de lanzamiento: 2009, 2010, 2011 y 2012.',
        'precio': 1500,
        'cantidad': 2,
        'imagen': '/static/img/Fumo_images/Deka_fumo_type/009.jpg',
    },
    {
        'id':2,
        'nombre': 'Hakurei Reimu Deka Versión Kourindou',
        'tipo': 'Fumo Deka',
        'rareza': 'Super Raro',
        'descripcion': 'Fumo-Fumo Deka de Hakurei Reimu, Año de lanzamiento: 2020.',
        'precio': 1500,
        'cantidad': 3,
        'imagen': '/static/img/Fumo_images/Deka_fumo_type/739.jpg',
    },
    {
        'id':3,
        'nombre': 'Kirisame Marisa Deka Versión 1',
        'tipo': 'Fumo Deka',
        'rareza': 'Super Raro',
        'descripcion': 'Fumo-Fumo Deka de Kirisame Marisa, Años de lanzamiento: 2009, 2010 y 2011.',
        'precio': 1500,
        'cantidad': 1,
        'imagen': '/static/img/Fumo_images/Deka_fumo_type/023.jpg',
    },
    {
        'id':4,
        'nombre': 'Kirisame Marisa Deka Versión Kourindou',
        'tipo': 'Fumo Deka',
        'rareza': 'Super Raro',
        'descripcion': 'Fumo-Fumo Deka de Kirisame Marisa, Años de lanzamiento: 2009, 2010 y 2011.',
        'precio': 1500,
        'cantidad': 4,
        'imagen': '/static/img/Fumo_images/Deka_fumo_type/740.jpg',
    },
    {
        'id':5,
        'nombre': 'Izayoi Sakuya Deka Versión 1',
        'tipo': 'Fumo Deka',
        'rareza': 'Super Raro',
        'descripcion': 'Fumo-Fumo Deka de Izayoi Sakuya, Año de lanzamiento: 2022.',
        'precio': 1500,
        'cantidad': 8,
        'imagen': '/static/img/Fumo_images/Deka_fumo_type/853.jpg',
    },
    {
        'id':6,
        'nombre': 'Scarlet Remilia Deka Versión 1',
        'tipo': 'Fumo Deka',
        'rareza': 'Super Raro',
        'descripcion': 'Fumo-Fumo Deka de Scarlet Remilia, Año de lanzamiento: 2011.',
        'precio': 1500,
        'cantidad': 7,
        'imagen': '/static/img/Fumo_images/Deka_fumo_type/124.jpg',
    },
   {
        'id':7,
        'nombre': 'Scarlet Remilia Deka Versión 1.5',
        'tipo': 'Fumo Deka',
        'rareza': 'Super Raro',
        'descripcion': 'Fumo-Fumo Deka de Scarlet Remilia, Año de lanzamiento: 2022.',
        'precio': 1500,
        'cantidad': 10,
        'imagen': '/static/img/Fumo_images/Deka_fumo_type/851.jpg',
    },
]

productos_puppet = [
{
        'id':1,
        'nombre': 'Hakurei Reimu Deka Versión Puppet',
        'tipo': 'Fumo Puppet',
        'rareza': 'Raro',
        'descripcion': 'Fumo-Fumo Puppet de Hakurei Reimu, Año de lanzamiento: 2009.',
        'precio': 1500,
        'cantidad': 3,
        'imagen': '/static/img/Fumo_images/Puppet_type/021.jpg',
},
{
        'id':2,
        'nombre': 'Kirisame Marisa Deka Versión Puppet',
        'tipo': 'Fumo Puppet',
        'rareza': 'Raro',
        'descripcion': 'Fumo-Fumo Puppet de Kirisame Marisa, Año de lanzamiento: 2009.',
        'precio': 1500,
        'cantidad': 5,
        'imagen': '/static/img/Fumo_images/Puppet_type/022.jpg',
},
]

productos_strap = [
{
        'id':1,
        'nombre': 'Hakurei Reimu Deka Versión Toy Strap',
        'tipo': 'Fumo Toy Strap',
        'rareza': 'Raro',
        'descripcion': 'Fumo-Fumo Toy Strap de Hakurei Reimu, Año de lanzamiento: 2020.',
        'precio': 1500,
        'cantidad': 3,
        'imagen': '/static/img/Fumo_images/Strap_type/745.jpg',
},
{
        'id':2,
        'nombre': 'Kirisame Marisa Deka Versión Toy Strap',
        'tipo': 'Fumo Toy Strap',
        'rareza': 'Raro',
        'descripcion': 'Fumo-Fumo Toy Strap de Kirisame Marisa, Año de lanzamiento: 2020.',
        'precio': 1500,
        'cantidad': 3,
        'imagen': '/static/img/Fumo_images/Strap_type/746.jpg',
},

]
