# Generated by Django 4.2.1 on 2023-07-07 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario_app', '0002_shoppingcartmodel_cartdetailmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoppingcartmodel',
            name='ammount',
        ),
    ]
