# Generated by Django 4.2.1 on 2023-07-07 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario_app', '0003_remove_shoppingcartmodel_ammount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppingcartmodel',
            name='creation_date',
            field=models.DateTimeField(),
        ),
    ]
